settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: Main entrance(CN)
    description: 'Official entrance for China Mainland users ' # default=empty
    url: 'https://www.weipien.club/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: Main entrance(Global)
    name: www.vpn.taxi
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.vpn.taxi'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Subscription-aa
    name: Subscription API Gateway
    url: 'https://clashcat.clashcat.workers.dev/'
    method: GET
    expectStatus: 200
